import type { Metadata } from "next";
import { Playfair_Display, Montserrat, Caveat } from "next/font/google";
import "./globals.scss";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/NavbarMain/Navbar";

const montserrat_init = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});
const playfair_display_init = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair_display",
});
const shadows_Into_Light = Caveat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-shadows_into_light",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat_init.variable} ${shadows_Into_Light.variable} ${playfair_display_init.variable}`}
      >
        <Navbar />
        {children}
        {/*  <Footer /> */}
      </body>
    </html>
  );
}
